language: python

jobs:
  include:
    - name: "Lint Check"
      language: python
      python: 3.6
      env:
        - TOX_ENV=lint

    - name: "Test on python 2.7"
      language: python
      python: 2.7
      env:
       - TOX_ENV=py27

    - name: "Test on python 3.6"
      language: python
      python: 3.6
      env:
        - TOX_ENV=py36
    
    - name: "Documentation build check"
      language: python
      python: 3.6
      env:
        - TOX_ENV=docs


install:
  - pip install tox

script: tox -e $TOX_ENV